[2016-03-13 13:23:09,956 root CRITICAL] Exception:Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)
[2016-03-13 13:23:09,956 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 724, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 853, in _GetServiceContent
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 543, in <lambda>
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1235, in InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1320, in GetConnection
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 897, in _VerifyThumbprint
 ThumbprintMismatchException: Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)

[2016-03-13 13:33:01,050 root CRITICAL] Exception:Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)
[2016-03-13 13:33:01,050 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 724, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 853, in _GetServiceContent
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 543, in <lambda>
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1235, in InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1320, in GetConnection
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 897, in _VerifyThumbprint
 ThumbprintMismatchException: Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)

[2016-03-13 13:34:00,492 root CRITICAL] Exception:Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)
[2016-03-13 13:34:00,493 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 724, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 853, in _GetServiceContent
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 543, in <lambda>
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1235, in InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1320, in GetConnection
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 897, in _VerifyThumbprint
 ThumbprintMismatchException: Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)

[2016-03-13 13:34:15,127 root CRITICAL] Exception:Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)
[2016-03-13 13:34:15,127 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 724, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 853, in _GetServiceContent
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 543, in <lambda>
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/VmomiSupport.py", line 352, in _InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1235, in InvokeMethod
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 1320, in GetConnection
   File "/build/mts/release/bora-2503622/compcache/pyvmomi/ob-2503340/publish/pyVmomi/SoapAdapter.py", line 897, in _VerifyThumbprint
 ThumbprintMismatchException: Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 3feee8756b8cf1f96e228b7daed54d8d008369c7 (server)

[2016-03-13 13:35:05,588 root CRITICAL] Exception:(vmodl.fault.HostNotConnected) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Connection failure',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
[2016-03-13 13:35:05,588 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 724, in Login
   File "/build/mts/release/bora-2503622/bora/build/esxcli/release/build/Session.py", line 859, in _GetServiceContent
 vmodl.fault.HostNotConnected: (vmodl.fault.HostNotConnected) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Connection failure',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

